POST http://localhost:8081/transaction/createtransaction
Content-Type: application/json

{
    "stock_name": "AMZ",
    "tran_type": "BUY",
    "tran_amount": 7000,
    "username": "tochiamanze"
}

###
GET http://localhost:8081/transaction/getAll
Content-Type: application/json

###
POST  http://localhost:8081/transaction/deleteAll


###
POST http://localhost:8081/user/signup
Content-Type: application/json 

{
    "username" : "tochiamanze",
    "email" : "cdon@gmail.com",
    "password" : "tochi12345"
}

###

POST http://localhost:8081/user/login
Content-Type: application/json 

{
    "username" : "JJJJJJJJJJJJJ",
    "password" : "J1234567"
}

###
GET http://localhost:8081/user/getAll
Content-Type: application/json

###

POST http://localhost:8081/user/editUser
Content-Type: application/json 

{
    "userId" : "65cd70c37211992d0f9028a5",
    "username" : "J1234567",
    "password" : "J1234567"
}

###
GET  http://localhost:8081/user/getUserById
Content-Type: application/json 

{
    "userId" : "65cd89467211992d0f9028d6"
}

###
POST  http://localhost:8081/user/deleteAll

###
GET http://localhost:8081/user/getUserCashBalance?userId=65cd86017211992d0f9028d0
Content-Type: application/json